apiVersion: "v1"
kind: Service
metadata: 
   name: "python-blue"
   labels: 
      app: "python-blue"
spec: 
   ports: 
      - port: 80
        name: webapp
        targetPort: 5000
   selector: 
      app: "python-blue-app"
   type: ClusterIP
