apiVersion: "apps/v1"
kind: Deployment
metadata: 
   name: "print-requests"
   labels: 
      name: "print-requests"
      app: "print-requests-app"
spec: 
   replicas: 3
   selector: 
      matchLabels:
         app: "print-requests-app"
   template: 
      metadata: 
         labels: 
            app: "print-requests-app"
      spec: 
         containers: 
            - name: "print-requests"
              image: danielcaldwell/print_requests:1.0
              ports: 
                 - containerPort: 5000
                   name: http
                   protocol: TCP

