---
apiVersion: extensions/v1beta1
kind: Ingress
metadata: 
   name: print-requests-ingress
spec: 
   rules: 
      - host: print-requests.amigocloud.com
        http:
           paths: 
              - backend: 
                   serviceName: print-requests
                   servicePort: 80 
