apiVersion: "v1"
kind: Service
metadata: 
   name: webapp
   labels: 
      name: webapp
      app: demoapp
spec: 
   ports: 
      - port: 80
        name: webapp
        targetPort: 5000
   selector: 
      name: webapp
      app: demoapp
   type: NodePort
